const images = {
  check: require('../assests/check.png'),
  cross: require('../assests/cross.png'),
  Profile: require('../assests/Profile.png'),
  edit: require('../assests/edit.png'),
  menu: require('../assests/menu.png'),
  search: require('../assests/search.png'),
  arrow_left: require('../assests/arrow_left.png'),
  arrow_right: require('../assests/arrow_right.png'),
  calendar: require('../assests/calendar.png'),
  book_open: require('../assests/book_open.png'),
  home: require('../assests/home.png'),
  instagram: require('../assests/instagram.png'),
  user: require('../assests/user.png'),
  plus_square: require('../assests/plus_square.png'),
  addPerson: require('../assests/addPerson.png'),
  book_open1: require('../assests/book_open1.png'),
  message_square: require('../assests/message_square.png'),
  emojione_fire: require('../assests/emojione_fire.png'),
  // Profile Icons
  chevron: require('../assests/Icons/chevron.png'),
  alarm: require('../assests/Icons/alarm.png'),
  data: require('../assests/Icons/data.png'),
  food: require('../assests/Icons/food.png'),
  settings: require('../assests/Icons/settings.png'),
  profileUser: require('../assests/Icons/profileUser.png'),
  clock: require('../assests/Icons/clock.png'),

  doc: require('../assests/Icons/doc.png'),
  plus: require('../assests/Icons/plus.png'),
  delete: require('../assests/Icons/delete.png'),
};
export default images;